Home task 3.6.4
DamirS09/places_surf pull request #2
Opened 2021-05-29 16:11 UTC by DamirKrg

Переименуйте файл main.dart в start.dart. Запустите проект. Почему результат именно таков?
Верните именование.
Ответ: Ломается программа так как main является точкой входа, а его нет.
В файле main.dart создайте виджет приложения. Назовите его App.
Ответ: сделал
В методе build() верните MaterialApp в поле home поставьте Stateless виджет из предыдущего домашнего задания(см. урок про виджеты). Рассмотрите его параметры. Задайте поле title. Запустите на Android. Где отобразится значение этого поля?
Ответ:  значение появляется посередине.
Перейдем к рассмотрению контекста. В вашем Stateless виджет создайте метод без аргументов, который будет возвращать context.runtimeType. Получится ли реализовать подобное в данном виджете?
Проделайте предыдущий пункт в рамках Stateful. В чем разница?
Ответ: Получается возвращает название widget откуда был вызван. Особую разницу не увидел.

2021-05-31 18:54 UTC, artem-zaitsev commented
Вы неверно выполнили послежнее задание - не widget.runtimeType, а "context.runtimeType".

2021-05-31 18:54 UTC, artem-zaitsev requested changes
Последнее неверно

2021-05-31 20:00 UTC, DamirKrg commented
> Последнее неверно

исправил, в statelessWidget просит создать context и выдает ошибку. А в statefulWidget все сработало так как в state есть BuildContext get context, выводит на экран StatefulElement

2021-06-02 03:44 UTC, dkrutskikh approved these changes

2021-06-21 10:42 UTC, closed without merging